In [1]:
#Frozen world
#stocastic model game reinforcement-learning

In [4]:
#register game 
from gym.envs.registration import register

register(
    id = 'FrozenLake-v1',
    entry_point = 'gym.envs.toy_text:FrozenLakeEnv',
    kwargs = {'map_name' : '4x4', 'is_slippery' :True}
)

In [6]:
import gym
import numpy as np
import pandas as pd

In [39]:
# set environment
game_env = 4 * 4
game_act = 4
Q = np.zeros((game_env,game_act))
dis = 0.99
rList = []
learning_rate = 0.85
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
env = gym.make('FrozenLake-v1')
for i in range(1000):
    state = env.reset()
    rAll = 0
    done = False
    while not done:
        #env.render()
        action = np.argmax(Q[state,:]+np.random.randn(1,game_act)/(i+1))
        new_state, reward, done,_ = env.step(action)
        Q[state,action] = (1-learning_rate) * Q[state,action] + \
        learning_rate * (reward + dis * np.max(Q[new_state,:]))
        state = new_state
        rAll += reward
        
    rList.append(rAll)

In [59]:
sum(rList)/10

64.8

In [46]:
list(map(lambda x : x*100,Q))

[array([ 1.63573309, 76.30931414,  1.5584072 ,  3.485397  ]),
 array([ 0.25574892,  0.14814089,  0.27308361, 58.95795727]),
 array([ 0.        ,  0.29908101,  0.82790649, 34.12293878]),
 array([ 0.26708736,  0.0250111 ,  0.07289212, 21.16395027]),
 array([85.42267241,  0.1858311 ,  0.13724631,  0.2065846 ]),
 array([0., 0., 0., 0.]),
 array([7.44927279e-02, 5.89405999e-03, 2.88397866e+01, 2.41081061e-05]),
 array([0., 0., 0., 0.]),
 array([ 0.19080085,  0.12633052,  0.15436135, 89.23286507]),
 array([ 0.07097766, 52.59756156,  0.62015721,  0.        ]),
 array([89.09602493,  0.        ,  0.25115736,  0.        ]),
 array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([7.09776555e-02, 7.25746527e-02, 8.78565000e+01, 3.82100391e-01]),
 array([ 0.        , 99.50108065,  0.        ,  0.        ]),
 array([0., 0., 0., 0.])]

In [ ]:
#Q-Network

In [57]:
np.identity(16)[1]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
np.identity(16)[1:2]

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
from keras.models import Seqeuntial
from keras.layers import Dense