In [4]:
#wx가 더 나을수도있다고함
#https://medium.com/acing-ai/how-i-build-an-ai-to-play-dino-run-e37f37bdf153

In [3]:
from PIL import ImageGrab
import numpy as np
import cv2

In [16]:
def grab_screen(_driver = None):
    #bbox = region of interest on the entire screen
    screen =  np.array(ImageGrab.grab(bbox=(40,180,440,400))) 
    image = process_img(screen)#processing image as required
    return image
def process_img(image):
    #game is already in grey scale canvas, canny to get only edges and reduce unwanted objects(clouds)
    # resale image dimensions
    image = cv2.resize(image, (0,0), fx = 0.15, fy = 0.10) 
    #crop out the dino agent from the frame
    image = image[2:38,10:50] #img[y:y+h, x:x+w] 
    image = cv2.Canny(image, threshold1 = 100, threshold2 = 200) #apply the canny edge detection
    return  image 

In [17]:
grab_screen()

array([[255, 255,   0,   0,   0,   0,   0,   0, 255, 255, 255, 255, 255,
          0,   0, 255, 255,   0,   0,   0, 255, 255, 255,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0, 255, 255, 255,   0, 255,
        255],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 

In [21]:
def grab_screen(_driver = None):
    #bbox = region of interest on the entire screen
    screen =  np.array((ImageGrab.grab(bbox=(100,200,300,400))) )
    #image = process_img(screen)#processing image as required
    print(screen)
    cv2.imshow("yes",screen)
    #return image
def process_img(image):
    #game is already in grey scale canvas, canny to get only edges and reduce unwanted objects(clouds)
    # resale image dimensions
    image = cv2.resize(image, (0,0), fx = 0.15, fy = 0.10) 

In [22]:
grab_screen()

[[[  0  29  61]
  [  0  29  61]
  [  0  29  61]
  ...
  [115  72  21]
  [102  60  18]
  [102  60  18]]

 [[  1  30  62]
  [  1  30  62]
  [  1  30  62]
  ...
  [113  70  20]
  [102  60  18]
  [105  63  18]]

 [[  1  30  62]
  [  1  30  62]
  [  1  30  62]
  ...
  [112  69  20]
  [102  60  18]
  [114  72  20]]

 ...

 [[  0  31  62]
  [  0  31  62]
  [  0  31  62]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0  31  62]
  [  0  31  62]
  [  0  31  62]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0  31  62]
  [  0  31  62]
  [  0  31  62]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
