In [2]:
class _Getch:
    def __init__(self):
        try:
            self.impl = _GetchWindows()
        except ImportError:
            try:
                self.impl = _GetchMacCarbon()
            except AttributeError:
                self.impl = _GetchUnix()

    def __call__(self): return self.impl()
class _GetchWindows:
    def __init__(self):
        import msvcrt

    def __call__(self):
        import msvcrt
        return msvcrt.getch()

In [ ]:
#gym.logger.set_level(40)
inkey = _Getch()
LEFT = 0
RIGHT = 1

arrow_keys = {
    b'd' :RIGHT,
    b'a' :LEFT,
}    

env = gym.make('CartPole-v0')

env.reset()
env.render()
for _ in range(100):
    key = inkey()
    if key != b'\x00':
        action = arrow_keys[key]
        env.step(action)
        env.render()


WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [2]:
import gym
env = gym.make('CartPole-v0')
env.reset()
done = False
while done == False :
    env.render()
    state, reward, done,_ = env.step(env.action_space.sample())


In [5]:
import gym

env = gym.make("CartPole-v0")
env.reset()
random_episodes = 0
reward_sum = 0
while random_episodes < 10:
    env.render()
    action = env.action_space.sample()
    observation,reward, done, _ = env.step(action)
    print(observation,reward,done)
    reward_sum += reward
    
    if done:
        random_episodes +=1
        print(reward_sum)
        reward_sum = 0
        env.reset()

[-0.00949905 -0.2059123  -0.00447438  0.32562772] 1.0 False
[-0.01361729 -0.01072693  0.00203817  0.03153714] 1.0 False
[-0.01383183 -0.20587805  0.00266892  0.32486243] 1.0 False
[-0.01794939 -0.4010379   0.00916616  0.61838582] 1.0 False
[-0.02597015 -0.59628668  0.02153388  0.9139415 ] 1.0 False
[-0.03789588 -0.40146253  0.03981271  0.62810349] 1.0 False
[-0.04592513 -0.59711685  0.05237478  0.93305426] 1.0 False
[-0.05786747 -0.79290483  0.07103587  1.24172467] 1.0 False
[-0.07372557 -0.59876301  0.09587036  0.97211336] 1.0 False
[-0.08570083 -0.79503163  0.11531263  1.2933071 ] 1.0 False
[-0.10160146 -0.60154847  0.14117877  1.03883662] 1.0 False
[-0.11363243 -0.79823524  0.1619555   1.37230028] 1.0 False
[-0.12959713 -0.99496892  0.18940151  1.7109461 ] 1.0 False
[-0.14949651 -0.80246037  0.22362043  1.48269891] 1.0 True
14.0
[ 0.0043972   0.15270317 -0.01073407 -0.29378804] 1.0 False
[ 0.00745127 -0.04226411 -0.01660983 -0.00450972] 1.0 False
[ 0.00660599 -0.23714396 -0.01670002

[ 0.07046289  0.75075219 -0.13305085 -1.34188207] 1.0 False
[ 0.08547793  0.94727374 -0.15988849 -1.67306069] 1.0 False
[ 0.1044234   1.14385048 -0.1933497  -2.01097201] 1.0 False
[ 0.12730041  1.34038772 -0.23356914 -2.35677577] 1.0 True
17.0
[ 0.02554547  0.21631999 -0.04299701 -0.26652586] 1.0 False
[ 0.02987187  0.41202838 -0.04832752 -0.57245436] 1.0 False
[ 0.03811244  0.21761619 -0.05977661 -0.29537931] 1.0 False
[ 0.04246477  0.02339512 -0.0656842  -0.02213191] 1.0 False
[ 0.04293267 -0.17072637 -0.06612684  0.24912514] 1.0 False
[ 0.03951814 -0.36484471 -0.06114433  0.52023913] 1.0 False
[ 0.03222125 -0.16891771 -0.05073955  0.2089326 ] 1.0 False
[ 0.02884289  0.02689166 -0.0465609  -0.09931448] 1.0 False
[ 0.02938073 -0.16753313 -0.04854719  0.17832269] 1.0 False
[ 0.02603006  0.02824872 -0.04498073 -0.12927136] 1.0 False
[ 0.02659504 -0.16620098 -0.04756616  0.14888829] 1.0 False
[ 0.02327102 -0.36061065 -0.0445884   0.4261938 ] 1.0 False
[ 0.0160588  -0.16488644 -0.03606452

0